Ÿservices:
  build-frontend:
    image: genuine-oj/builder:latest
    build:
      context: .
      dockerfile: ./dockerfile/Dockerfile.build-frontend
      args:
        USE_MIRROR: ${USE_MIRROR:-false}
    volumes:
      - ./data/frontend/:/root/frontend-dist/
      - ../frontend-naive:/root/frontend-local
    environment:
      USE_MIRROR: ${USE_MIRROR:-false}
      USE_LOCAL_SOURCE: ${USE_LOCAL_SOURCE:-false}Ÿ*cascade08"(5ac4ce5149d5df03259d8e59c714ddf813d0c19c2.file:///root/deploy/docker-compose.builder.yml:file:///root/deploy